// <auto-generated />
using System;
using ExempleSupportPortail.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExempleSupportPortail.Server.Migrations
{
    [DbContext(typeof(SupportContext))]
    [Migration("20230120145733_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExempleSupportPortail.Shared.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArea"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdArea");

                    b.ToTable("Area", (string)null);

                    b.HasData(
                        new
                        {
                            IdArea = 1,
                            Title = "IT"
                        },
                        new
                        {
                            IdArea = 2,
                            Title = "Facilities"
                        },
                        new
                        {
                            IdArea = 3,
                            Title = "HR"
                        });
                });

            modelBuilder.Entity("ExempleSupportPortail.Shared.Issue", b =>
                {
                    b.Property<int>("IdIssue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIssue"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdIssue");

                    b.HasIndex("AreaId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Issue", (string)null);

                    b.HasData(
                        new
                        {
                            IdIssue = 1,
                            AreaId = 1,
                            Comment = "Did you check the power cable?",
                            DateCreated = new DateTime(2023, 1, 20, 15, 57, 33, 135, DateTimeKind.Local).AddTicks(3828),
                            Description = "I can't turn it on",
                            StatusId = 2,
                            Subject = "My computer is broken",
                            UserId = 1
                        },
                        new
                        {
                            IdIssue = 2,
                            AreaId = 2,
                            DateCreated = new DateTime(2023, 1, 20, 15, 57, 33, 135, DateTimeKind.Local).AddTicks(4019),
                            Description = "I can't open it",
                            StatusId = 1,
                            Subject = "The door is broken",
                            UserId = 1
                        },
                        new
                        {
                            IdIssue = 3,
                            AreaId = 3,
                            Comment = "I approve this leave request",
                            DateCreated = new DateTime(2023, 1, 20, 15, 57, 33, 135, DateTimeKind.Local).AddTicks(4022),
                            Description = "I need to leave for 2 weeks",
                            StatusId = 3,
                            Subject = "Leave request",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ExempleSupportPortail.Shared.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStatus");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            IdStatus = 1,
                            Title = "In progress"
                        },
                        new
                        {
                            IdStatus = 2,
                            Title = "On hold"
                        },
                        new
                        {
                            IdStatus = 3,
                            Title = "Closed"
                        });
                });

            modelBuilder.Entity("ExempleSupportPortail.Shared.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUser");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            Login = "jdoe",
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("ExempleSupportPortail.Shared.Issue", b =>
                {
                    b.HasOne("ExempleSupportPortail.Shared.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExempleSupportPortail.Shared.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExempleSupportPortail.Shared.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExempleSupportPortail.Shared.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
